### ISSUE TITLE
File docker/compose/gelk.yml has developer-dependent files

### ISSUE THREAD

**Issue by jgbarah** [grimoirelab/GrimoireELK#1]
The following lines in docker/compose/gelk.yml:

```
nginx:
    image: nginx
    links:
        - gelk
    ports:
        - 9181:9181
    volumes:
        - ~/devel/GrimoireELK/docker/compose/rq-dash-nginx.conf:/etc/nginx/nginx.conf:ro
        - ~/devel/GrimoireELK/docker/compose/rq-dash-password:/etc/nginx/rq-dash-password:ro
```

The two lines in volumes assume that this repository has been cloned under ~/devel/GrimoireELK, but that's probably only the place where the developer cloned it. In general, it should be relative to the place where it is cloned in each environment.

I couldn't find a way for specifying relative paths for this file (or at least, none that worked for me), that's why I don't include a pull request. But when I changed those two paths to the actual location of my repo, I could finally run the docker containers as intended.
